version: '2'
services:
  php:
    build:
        context: .
        dockerfile: Dockerfile-php
    container_name: php
    volumes_from:
      - code
    
  mysql:
    image: mysql:5.7.22
    container_name: db
    ports:
    - 3306:3306
    volumes:
      - /var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=fred     
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - 8080:80
    links:
      - mysql:db


      
    